import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { FrameProvider } from "@/context/FrameContext";
import "./globals.css";
import { FrameInit } from "@/components/FrameInit";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakartaSans.variable}`}>
      <body>
        <FrameProvider>
          {children}
        </FrameProvider>
      </body>
    </html>
  );
}
