name = "fc-connections-api"
main = "src/index.js"
compatibility_date = "2023-10-25"
compatibility_flags = ["nodejs_compat"]

# Bind a D1 database
[[d1_databases]]
binding = "DB" # Available in your Worker as env.DB
database_name = "fc_connections"
database_id = "f0611df6-149e-4198-a781-fdb85136ac35"

# Environment variables
[vars]
# Public variables can be defined directly in the toml
APP_PUBLIC_ENV = "production"