name = "fc-connections-api"
main = "src/index.js"
compatibility_date = "2023-10-25"
compatibility_flags = ["nodejs_compat"]

# Bind a D1 database
[[d1_databases]]
binding = "DB" # Available in your Worker as env.DB
database_name = "fc_connections"
database_id = "993be606-bc98-4af2-83a4-f76593b103fd"

# Environment variables
[vars]
# Public variables can be defined directly in the toml
APP_PUBLIC_ENV = "production"