name = "fc-connections-api"
main = "src/index.js"
compatibility_date = "2023-10-25"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"

# Configure Bun as the runtime
[build]
command = "bun run build"

# Use Bun for builds
[build.upload]
format = "modules"
main = "./index.js"

# Development settings
[dev]
port = 8787

# Bind a D1 database
[[d1_databases]]
binding = "DB" # Available in your Worker as env.DB
database_name = "fc_connections"
database_id = "$FC_CONNECTIONS_DB_ID" # This value comes from .env at deploy time

# Environment variables
[vars]
# Public variables can be defined directly in the toml
APP_PUBLIC_ENV = "production"

# Private vars should be set using wrangler secrets or from .env at deploy time 